### ISSUE TITLE
Setup git for source code control and deploy livesite from github

### ISSUE THREAD

**Issue by Hoannv** [gemstoneit/metafit2014#1]

**Comment by Hoannv** [comment]
@jamiemax: I just create ssh private and public key for root user. You should add this key to your ssh keys in order to pull commit from github to livesite

public key is locate in vi /root/.ssh/id_rsa.pub. You only need open this file and copy content to your ssh keys

On live site, you only need git pull origin master for fetching the latest commit

I also create new branch "develop" for development. All commit must be push to "develop" branch and must test before merge to master branch.

**Comment by Hoannv** [comment]
I also add a script for deployment. After you pull latest commits from github to livesite, you can run script. It helps you run some command for installing assets file, dumping assets file, updating database and remove prod cache

bash app/scripts/deploy.sh

**Comment by Hoannv** [comment]
@jamiemax: I tried to setup site on local. But site is very difference with livesite. Do you have any instruction for setup site ?


![screenshot from 2015-01-27 11 11 20](https://cloud.githubusercontent.com/assets/1846777/5913370/624f7fb4-a615-11e4-8dfd-71b319f3baf9.png)
![screenshot from 2015-01-27 11 11 38](https://cloud.githubusercontent.com/assets/1846777/5913372/662443c2-a615-11e4-97f6-4539f34194f4.png)

**Comment by jamiemax** [comment]
Sorry i don't - my local copy seems to work fine. Do you have Symlinks set up? I think the assets in the web directory need to be symlinked somewhere

**Comment by Hoannv** [comment]
yes, I tried symlinks and it's working. But login page is still not working. I don't know why login page on live site has layout.

**Comment by jamiemax** [comment]
think the login pages are stored at vendor/sonata-project/user-bundle/resources/views/security
