### ISSUE TITLE
Notify site owner when a new user signs up through their site

### ISSUE THREAD

**Issue by jamiemax** [gemstoneit/metafit2014#15]
Currently in src/Blogger/BlogBundle/Event/PayPalListener.php - you have some code after line 125 which is designed to send an email to the Australian site manager when an Australian coach signs up (It checks if the $countryCode variable from PayPal is 'AU')

The objective:
We want the site to send an email to the manager of the region where the user is signing up from, for example if $countryCode is 'DK' it should look up the denmark 'Site' entity, find the 'paypal_email' property and send a message to that email address with details of the user who signed up or made a purchase.

(Currently the email is not coming through, according to the Australian manager - this may be a problem with sendmail - please can we use SwiftMailer instead)

**Comment by Hoannv** [comment]
I understand. I will check and fix this problem.

**Comment by Hoannv** [comment]
@jamiemax : pls review it before deploy to live site.
