### ISSUE TITLE
Give Super Admin users the ability to change user roles through the Admin interface

### ISSUE THREAD

**Issue by jamiemax** [gemstoneit/metafit2014#16]
When we logged in with the "admin" account we used to be able to edit users roles - this has now disappeared.

Would you be able to add this back in?

**Comment by Hoannv** [comment]
we've already used group for managing role. I think we don't need role any more. I will set up group then you can manage user's roles by group.

**Comment by Hoannv** [comment]
the reasons are:

1. sonata_admin: handler: sonata.admin.security.handler.role. We've enabled sonata's security by role. There are many roles as you can see in email admin.
2. there are some bugs with sonatauserbundle. Like https://github.com/sonata-project/SonataUserBundle/issues/461, https://github.com/sonata-project/SonataUserBundle/search?q=remove+roles&type=Issues&utf8=%E2%9C%93

**Comment by Hoannv** [comment]
Now super admin can create new group. During create new group, super admin can add role to this group.
Then add user to this group, user will have role in this group.

**Comment by Hoannv** [comment]
@jamiemax : pls try and give me feedback.

**Comment by jamiemax** [comment]
this is done now
