### ISSUE TITLE
Set up course date grouping functionality

### ISSUE THREAD

**Issue by jamiemax** [gemstoneit/metafit2014#18]

**Comment by jamiemax** [comment]
We need to be able to group events, for example on the Australia site we need to be able to add two groups - "Australia" and "New Zealand". In future we will have a USA site which will need two groups "East Coast" and "West Coast"

Essentially when you go on to the Events page, as user will see a tab for each group, and they will be able to navigate between them.

**Comment by Hoannv** [comment]
site has multiple groups
site has multiple events

group:event is M:N relationship.

I think we should add new entity name: group (has field: name, site)

**Comment by Hoannv** [comment]
time for it about: 4-5 hours

**Comment by Hoannv** [comment]
@jamiemax: can you theme for frontend ? I will integrate with backend when frontend is done.

**Comment by jamiemax** [comment]
i've now fixed this
