### ISSUE TITLE
IPN email issue

### ISSUE THREAD

**Issue by Hoannv** [gemstoneit/metafit2014#19]
one other issue is that Daniel in Australia doesn't seem to be getting emails when subscribers sign up on paypal (see PaypalLIstener.php at line 156) - any idea why this might be?

**Comment by Hoannv** [comment]
@jamiemax: you can test this function now.

**Comment by jamiemax** [comment]
can we make sure that support@metafit-training.com is copied in on all these emails so we can test?

**Comment by Hoannv** [comment]
these emails are forwarded to this email. You can start testing now.

**Comment by jamiemax** [comment]
ok thanks - could you show me where the code is for this? at line 176 it looks like the subscription notifications are only going to the site manager

**Comment by Hoannv** [comment]
yes, lines 90-94 in Blogger\BlogBundle\Service\Mail.php file
