### ISSUE TITLE
Email confirmations for users who book events

### ISSUE THREAD

**Issue by jamiemax** [gemstoneit/metafit2014#20]
We need to send an email confirmation to users who book events. The email will be different depending on what site the user has booked through (Australia, UK, etc). The site owner should be CC'd on the email. The email for the Australian version will be:

“Subject heading: Metafit Course Confirmation
Hi (insert name),
 
Congratulations on enrolling to become a Metafit Coach.
 
Date: (insert date)
Location: (insert location)
Times: (insert times) – having an option to input course times data would be very useful
 
Further details can be found at here www.facebook.com/metafitaustralia/events (maybe hyperlink the sentence). Updates are made on this page so make sure you tick ‘ Going’ to get these notifications.
 
What to wear: Please come along in gym gear ready to workout, and also a change of clothes if you want to freshen up. We will be doing a masterclass to kick things off, so expect to work hard.
 
What else to bring: Lunch/ Snacks/ water, Notepad/ Pen and lots of energy.
If you have any further questions, please don’t hesitate to contact daniel@metafit-australia.com or call 0438103608”

**Comment by Hoannv** [comment]
ET is 2-3 hours

**Comment by Hoannv** [comment]
@jamiemax I enabled confirmation email for Australia's site. You can start review. If you need email for other's country, pls send me email template for these countries.

**Comment by jamiemax** [comment]
this all looks fine to me, can we make this live please?

**Comment by Hoannv** [comment]
ok. I deployed on live site

**Comment by jamiemax** [comment]
On the automatic emails, the "Times" variable is not picking up the correct data. Could you look into this?

**Comment by jamiemax** [comment]
ok think I've fixed this. no worries
