### ISSUE TITLE
Add a "host a course page"

### ISSUE THREAD

**Issue by jamiemax** [gemstoneit/metafit2014#21]
Add a new page to the Australian site only, with the following content:

A REAL HIIT WORKOUT – Over 6000 coaches worldwide
No equipment, no gimmicks, no choreography. Simple, highly effective and ONLY 30 minutes. 
Hosting a Metafit workshop is a great opportunity for health clubs, PT studios and gyms to bring the original 30minute branded HIIT workout to their clients.
1. NO LICENSE FEES!  There is no monthly fee for a facility to use the trademarked Metafit name and logo, as long as the coaches have been trained by Metafit Master Coach and maintains a current coach subscription.
2.  ACTUAL SCIENCE - Metafit was developed over 8 years ago by former Royal Commando and National Gymnast. The workshop will dispel some fitness myths and coaches will learn the science behind Metafit and how high intensity interval training is most effectively executed.
3.  OVER 6000 COACHES- Metafit is a refreshing honest approach to fitness. It’s not overly complicated but that’s why it works. There are over 6000 qualified Metafit coaches worldwide. Metafit is a tough workout but it is easily adaptable for all levels of ability. Both qualified coaches and their clients love Metafit and keep coming back for more.
4. MARKETING - Once approved, we will provide your facility with posters, flyers as well as exposure via all of our Social Media channels.
Just simply click the link below to get your facility qualified as an Authorized Metafit Location and our Education Director will contact you within 24-48 hours to get your Metafit Instructor Training scheduled on the calendar!
HOST A COURSE

**Comment by jamiemax** [comment]
could i have an estimate for this?

**Comment by dantulloch** [comment]
2 hours fully designed to suit the current site's styling (+ responsive of course)
