### ISSUE TITLE
Multi level pricing

### ISSUE THREAD

**Issue by jamiemax** [gemstoneit/metafit2014#22]
For courses (events) we want to be able to add a discount price for people who book early

For example we might sell a course for £100 until a certain date, at which point it would go up to £200 automatically.

Do you think 10 hours would be enough for this?

**Comment by Hoannv** [comment]
yes. I think it can. ET is about 8 hours.

**Comment by jamiemax** [comment]
@Hoannv we have confirmation on this so please go ahead as soon as possible.

**Comment by Hoannv** [comment]
@jamiemax I enable multiple level pricing for event. I add three new fields called "discount price, discount start, discount end". You must fill these fields with valid values. Event will be applied new price if time is from discount start to discount end period.

**Comment by jamiemax** [comment]
thanks for this - the functionality looks good but we need something on the frontend to make it obvious that this is a discounted price. so for example having the regular price crossed out, next to the discounted price. @dantulloch - would you be able to modify the template to acheive this?

**Comment by Hoannv** [comment]
@dantulloch you can use a sample prices. I will fill real prices after you finish.

**Comment by Hoannv** [comment]
continue update theme on #28

**Comment by jamiemax** [comment]
hi hoan, on this - we need to show the discounted price and the normal price in two extra columns on the events list page metafit-training.com/events
could you update the controller and the template to show this data?

**Comment by Hoannv** [comment]
yes, I update it now
