### ISSUE TITLE
Users should only be able to UNsubscribe and REsubscribe once

### ISSUE THREAD

**Issue by jamiemax** [gemstoneit/metafit2014#24]
Sometimes users unsubscribe and then resubscribe multiple times. We don't want to allow them to do this. If they try and resubscribe more than once then they should be blocked from doing so, and the site manager should be notified

**Comment by Hoannv** [comment]
ok, we need function to log this action, then block users if they resubscribe multiple times.

ET is 4-5 hours.

**Comment by jamiemax** [comment]
@Hoannv the client has approved this so please go ahead. thanks.

**Comment by Hoannv** [comment]
User subscribes on http://metafit-training.com/ website. And user unsubscribes on Paypal.
Next time, user subscribes and then unsubscribes...

Is it the situation on requirement ?

**Comment by Hoannv** [comment]
@jamiemax can you confirm my question

**Comment by jamiemax** [comment]
ok so the current situation is:

users can subscribe and unsubscribe unlimited times

requirement is:

a user can do the following:

1. subscribe
2. unsubscribe
3. subscribe
4. unsubscribe
5. at this point they can NO LONGER subscribe through the website - if they go to the "subscribe" page they will get a message saying "You have subscribed and unsubscribed the maximum number of times - please contact <site manager email> if you need to subscribe again"

**Comment by jamiemax** [comment]
hi hoan, did you manage to work on this?

**Comment by Hoannv** [comment]
do you know how detect user subscribed ? I checked but I didn't know how detect an user subscribed or not. I couldn't test on my local for subscription function.

**Comment by jamiemax** [comment]
?Subscription is when they start paying the monthly fee on paypal, so when they upgrade from "New Coach" to a "Coach". This is triggered by the subscr_payment IPN

________________________________

**Comment by Hoannv** [comment]
and how an user unsubscribe ?

**Comment by jamiemax** [comment]
?that's when they cancel their subscription on paypal, and we get a "subscr_eot" IPN

________________________________

**Comment by Hoannv** [comment]
do you agree if we use new subscription entity for logging user subscribes events ?

And there are many scenarios of subscription like:
subscribe - unsubscribe - unsubscribe - subscribe - unsubscribe ..

That's why I think we should use new subscription for check user's behaviors

**Comment by jamiemax** [comment]
Yes I agree. Each time a user subscribes it should create a new subscription entity which we could count in order to determine whether they should be able to resubscribe. If more than two subcription entities exist for the user then we block them from subscribing. agreed?

**Comment by jamiemax** [comment]
we should have the following fields:

subscription_id
subscription_type
subscription_status
+ a foreign key: user

**Comment by Hoannv** [comment]
agreed. I created table. I will create entity soon

**Comment by jamiemax** [comment]
just had a look at the table - we need a column for the subscription ID - this is the subscr_id field in the paypal IPN request. When the subscription entity is created this should be populated with the subscr_id value from paypal.

also...

when a subscr_payment IPN is received, the status should be set to ACTIVE - 
when a recurring_payment_suspended_due_to_max_failed_payment or subscr_cancel or subscr_eot IPN is received the status should be set to DISABLED

**Comment by Hoannv** [comment]
Hi @jamiemax 

I implemented logic for Users should only be able to UNsubscribe and REsubscribe once. You can check it before deploy.
