### ISSUE TITLE
Statistics page in the admin

### ISSUE THREAD

**Issue by jamiemax** [gemstoneit/metafit2014#25]
Could we have a statistics page in the admin, showing:

Total number of New Coaches
Total number of Coaches
Number of signups in the last month
Product purchases in the last month

**Comment by Hoannv** [comment]
yes, I will implement a block and show it on dashboard. ET is 2-3 hours.

**Comment by jamiemax** [comment]
great - @dantulloch - could you give an estimate of how long it would take to style this?

**Comment by dantulloch** [comment]
I'd say an hour but I haven't styled the backend admin yet so maybe slightly more

**Comment by Hoannv** [comment]
I think we don't need to style this block. Because this block only contains
some simple rows.

Best Regards,

*Hoan Nguyen*

**Comment by dantulloch** [comment]
Hi Hoan. No problem, I assumed there was some kind of built in styling there but I wasn't sure if Jamie wanted something extra. Best, Dan

**Comment by Hoannv** [comment]
yes, admin has used twitter bootstrap. I can use some built widgets for it.

And I think we should use twitter bootstrap for frontend too. It supports us many built widgets

**Comment by Hoannv** [comment]
@jamiemax Do you know how to count total purchased products correctly? I've already added block to admin dashboard. You can view it now.

**Comment by Hoannv** [comment]
I think we should count on transaction page.

**Comment by Hoannv** [comment]
@jamiemax this block is done. You can view it on admin dashboard http://metafit-training.com/admin/dashboard

**Comment by jamiemax** [comment]
thanks - all looks good.

just wondered what are the numbers based on? have we really had 700 new subscribers in the last month?

**Comment by Hoannv** [comment]
Number of signups in the last month is based on "created_at" field on 'fos_user_user' table

**Comment by jamiemax** [comment]
ok great. can we have this site specific? so when you're logged in as a super admin you see all the data, but when you're logged in as a site manager you only see the data for your site?

**Comment by Hoannv** [comment]
yes, we can.

**Comment by jamiemax** [comment]
hi Hoan, sorry can we change this so that the number of New Coaches shows users who are ONLY part of the new coach group. so if a user is in 'New Coach' and 'Coach' - they would show up in the 'Coach' statistics but not the 'New Coach' statistics

**Comment by Hoannv** [comment]
I agreed with it.

**Comment by Hoannv** [comment]
This request is implemented.
