### ISSUE TITLE
Mailchimp request times out when an email is sent to many users

### ISSUE THREAD

**Issue by jamiemax** [gemstoneit/metafit2014#26]

**Comment by Hoannv** [comment]
yes, when you send email to "ROLE_USER" users, this issue will happens. It's because you subscribe too many emails on request.

My solution is:
1. Create different lists (list admin, list site manager, list user ..) on mailchimp
2. Subscribe users to list on mailchimp when user registers or is changed email
3. Send mail to list user on mailchimp. So we don't need subscribe users when send email

Estimation time for my solution about 6-7 hours

**Comment by jamiemax** [comment]
thnks for this - I will ask the client and get back to you

**Comment by jamiemax** [comment]
@Hoannv - the client has approved this so please go ahead

**Comment by Hoannv** [comment]
I update process of subscribe an email to mailchimp.

Now, when user registers and changes email address, user's email will be pushed to mailchimp, and the old email will be deleted.

I create a send button on email edit page on admin dashboard. Email is only sent when admin presses send button.

@jamiemax you can ask client verify new function now.

**Comment by jamiemax** [comment]
ok that's great. we need to send mail to users based on roles though, for example how do we send emails to only New Coaches or only Coaches?

**Comment by jamiemax** [comment]
there's only one list on mailchimp right?

**Comment by Hoannv** [comment]
function works same as int the past. Admin selects role and click send.

If admin selects "New coach" role, email will be sent to all users has "new coach" role.

**Comment by Hoannv** [comment]
yes, there is only list on mailchimp.

**Comment by jamiemax** [comment]
ok so users get added to mailchimp when they sign up to the site...
when we send an email from the site it sends an array of those users email addresses to mailchimp, creates a segment, and sends an email only to those users...
my question is, will this not still cause a timeout? we're still sending an array of 3000 email addresses to mailchimp?

**Comment by Hoannv** [comment]
no, because in old code, we subscribe each email to mailchimp list. So if we have 3000 email, we need 3000 requests for subscribe. It's very waste of time.

when we send email to segment, we send a bundle of email (max is 10000 emails / request). So there is no problem with send email to segment.

**Comment by jamiemax** [comment]
ok thanks, that's fine then. i'll close this issue
