### ISSUE TITLE
discount codes

### ISSUE THREAD

**Issue by jamiemax** [gemstoneit/metafit2014#28]

**Comment by jamiemax** [comment]
@Hoannv  we want to allow site managers to offer specific discount codes to users who book course. so they might create a code "XDHIFIE35KNFE" which can be inputted at checkout and which would give the user 30% off. Could you give a quote for this functionality

**Comment by Hoannv** [comment]
@jamiemax discount code has two types: percentage discount (30%) and amount discount (-$10). Do  they want both of these types?

And there are some pages have payment action. Do they need discount function for all of these pages ?

**Comment by jamiemax** [comment]
i will check with the client as to whether they want both percentages and fixed amounts. I'll get back to you as soon as I know

this is only required for EVENT purchases, not tracks or subscriptions.

**Comment by Hoannv** [comment]
agreed

**Comment by jamiemax** [comment]
we want fixed amounts for these, not percentages. please go ahead with this

**Comment by Hoannv** [comment]
I implemented promotion function. You can pull source code, set up a valid promotion for a specific event and then review function.

Pls update theme for promotion input as your expectation.
