### ISSUE TITLE
Adding site-specific tracking codes

### ISSUE THREAD

**Issue by jamiemax** [gemstoneit/metafit2014#31]
We want to be able to add tracking codes (e.g. Google analytics) to specific sites, so we would have a different one for metafit-training.com and for metafit-australia.com, etc. This does NOT need to be editable through sonata admin.

Can you quote for this?

**Comment by Hoannv** [comment]
It takes 1 hour. You should send me google analytic account

**Comment by jamiemax** [comment]
Hi Hoan - ok thanks. I will let you know if we get confirmation from the client. Here is the code (it is actually google remarketing, not google analytics:



<script type="text/javascript">
/* <![CDATA[ */
var google_conversion_id = 957703328;
var google_custom_params = window.google_tag_params;
var google_remarketing_only = true;
/* ]]> */
</script>
<script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">
</script>
<noscript>
<div style="display:inline;">
<img height="1" width="1" style="border-style:none;" alt="" src="//googleads.g.doubleclick.net/pagead/viewthroughconversion/957703328/?value=0&amp;guid=ON&amp;script=0"/>
</div>
</noscript>

**Comment by jamiemax** [comment]
<script type="text/javascript">
/* <![CDATA[ */
var google_conversion_id = 957703328;
var google_custom_params = window.google_tag_params;
var google_remarketing_only = true;
/* ]]> */
</script>
<script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">
</script>
<noscript>
<div style="display:inline;">
<img height="1" width="1" style="border-style:none;" alt="" src="//googleads.g.doubleclick.net/pagead/viewthroughconversion/957703328/?value=0&amp;guid=ON&amp;script=0"/>
</div>
</noscript>

**Comment by jamiemax** [comment]
OK I've skyped it to you
