### ISSUE TITLE
optimising the "find a coach" SQL query

### ISSUE THREAD

**Issue by jamiemax** [gemstoneit/metafit2014#33]
@Hoannv is this something you can help with? The find a coach feature runs very slowly and I think the problem is the very complex SQL query that has to run each time. do you know of a way to optimise this?

**Comment by Hoannv** [comment]
It takes 4-6 hours for optimize.

**Comment by jamiemax** [comment]
@hoan - how fast do you think you could get this to run?

**Comment by Hoannv** [comment]
I believe that we should improve query (1 hour for my suggestion)
1. Add constraint: same site to query. If user is from aus, we only search coach from aus. 
2. remove join with usermeta table (> 35k)
JOIN fos_user_user
                ON latlong.user = fos_user_user.id
                
                LEFT JOIN usermeta AS firstname
                    ON firstname.user_id = latlong.user
                    AND firstname.field_id = '15'
                LEFT JOIN usermeta AS lastname
                    ON lastname.user_id = latlong.user
                    AND lastname.field_id = '16'
                LEFT JOIN usermeta AS image
                    ON image.user_id = latlong.user
                    AND image.field_id = '11'
                LEFT JOIN usermeta AS address1
                    ON address1.user_id = latlong.user
                    AND address1.field_id = '2'
                LEFT JOIN usermeta AS address2
                    ON address1.user_id = latlong.user
                    AND address1.field_id = '3'
                LEFT JOIN usermeta AS address3
                    ON address1.user_id = latlong.user
                    AND address1.field_id = '4'
                LEFT JOIN usermeta AS postcode
                    ON postcode.user_id = latlong.user
                    AND postcode.field_id = '5'
                LEFT JOIN usermeta AS public
                    ON public.user_id = latlong.user
                    AND public.field_id = '10'

**Comment by jamiemax** [comment]
@Hoannv  OK - however the problem is that we need the usermeta in order to show the user's address on the results page - how would you resolve that?

**Comment by Hoannv** [comment]
we'll get usermeta data later after you find closest users' ids.

**Comment by jamiemax** [comment]
ok yeah i understand, how soon could we get this done?

**Comment by Hoannv** [comment]
I'll develop it this weekend and can be available next week

**Comment by jamiemax** [comment]
ok brilliant, thanks
