### ISSUE TITLE
Emails to customers when subscriptions are cancelled/suspended/failed

### ISSUE THREAD

**Issue by jamiemax** [gemstoneit/metafit2014#34]
Hi Hoan.

We want to set up some new notification emails to customers whose payments have failed or whose subscriptions have been cancelled? I've included the copy for the various transaction types:

Do you think you could do this in 2 hours?

subscr_failed

Hi [first and last name]

Your Metafit subscription fee processed on [failed date] has failed. PayPal will try and process this payment again in 5 days.

Payment failure is generally due to one of these three reasons;

1.there are insufficient funds in the PayPal account
2.there are insufficient funds in the bank account that backs the PayPal account
3.the credit card that funds the PayPal account has expired 

To update your credit or debit card;

1. Log in to your PayPal account.

2. Click Profile near the top of the page.

3. Click My money.

4. Click Update beside 'Credit and Debit card'.

5. Click Edit or Update expiry date under ‘Action’.

6.  Enter your new expiry date and click Save.

Please note: On the third payment failure, your Metafit subscription will be suspended.

For more details on PayPal recurring payments visit www.paypal.com.au.

If you have any further questions, please don’t hesitate to ask.

Kind Regards

Team Metafit 
[email of site manager]

 

 

recurring_payment_suspended_due_to_max_failed_payment

Hi [first and last name]

Your Metafit subscription processed on [failed date] has failed for the third consecutive time resulting in suspension.

Your Metafit account will be locked until your subscription is reactivated.

To reactivate your Metafit Subscription;

Log into your PayPal account and go to Profile -> My Money.

In the row for 'My preapproved payments' click 'Update'.

Here you will see a list of all of your recurring payments.  Find the subscription you need to reinstate and click on the title.  

The next page will show you all the details of this subscription. Click 'Re-activate' to re-activate your subscription.

For more details on PayPal suspended subscriptions visit www.paypal.com.au.

If you have any further questions, please don’t hesitate to ask.

Kind Regards

Team Metafit
[email of site manager]

 

 

subscr_cancelled OR subscr_eot

Hi [first and last name]

Your Metafit Subscription has been cancelled.

We hope you and your clients have enjoyed using our workouts.

As a qualified Metafit coach, you are able to re-subscribe at any point within the next 12 months.

If you have any feedback please contact daniel@metafit-australia.com, we’d love to hear from you.

Yours in Health and Fitness

Team Metafit
[email of site manager]

**Comment by Hoannv** [comment]
My estimation is 3 hours.

**Comment by jamiemax** [comment]
ok no problem, please go ahead with this

**Comment by Hoannv** [comment]
We have an issue with recurring_payment_suspended_due_to_max_failed_payment event. We have a requirement when receive "recurring_payment_suspended_due_to_max_failed_payment" event:
"Your Metafit account will be locked until your subscription is reactivated."

When we receive above event, we lock user's account. And when user reactivates subscriptions, we unlock account in "subscr_payment" event. But we can't make sure that paypal will send us an "subscr_payment" event or not.

http://stackoverflow.com/questions/14289621/is-there-a-paypal-ipn-when-a-suspended-subscription-is-reactivated

**Comment by jamiemax** [comment]
There is a setting within paypal where you can set it to send IPNs for all events that happen on that account. I have done this, so it should be ok.

**Comment by Hoannv** [comment]
thanks @jamiemax. You can review new emails now.

**Comment by jamiemax** [comment]
this looks fine to me. i'll close the issue for now and let you know if we have any trouble

**Comment by jamiemax** [comment]
@Hoannv actually, are these emails being sent to the customers or to the site manager? they should go to the customer

**Comment by Hoannv** [comment]
yes. they are sent to customer

**Comment by jamiemax** [comment]
great, thank you

**Comment by Hoannv** [comment]
and they are also bcc to site manager.

**Comment by jamiemax** [comment]
cool, that's great
