### ISSUE TITLE
Stop redirecting users based on their country

### ISSUE THREAD

**Issue by jamiemax** [gemstoneit/metafit2014#35]
We need to remove the forced redirection feature on the site (the header('Location: ...') line on GetSite.php), as it is really bad for SEO

Instead, we want to display a banner suggesting that the users visits their local site. We want it to look something like the screenshot below.

The payment pages (book a course, subscribe, product purchase, etc) should not allow users to purchase outside of their country. They should simply display a message asking the user to visit their local site.

Could you give me a quote for this functionality?

![shoeaholics-screenshot](https://cloud.githubusercontent.com/assets/6630957/7020410/a4fd2db6-dd10-11e4-9c23-399b3936f7de.png)

**Comment by Hoannv** [comment]
It needs 2-4 hours

**Comment by jamiemax** [comment]
ok great. just to clarify - we still need to store the site ID, so if someone accesses metafit-training.com the site_id will be 1, if the access metafit-australia.com the site_id will be 2, etc, etc,

**Comment by jamiemax** [comment]
I will ask the client and get back to you

**Comment by jamiemax** [comment]
client has approved this, please go ahead

**Comment by Hoannv** [comment]
I commit on branch MF35, pls checkout.

If you need display different host message on a page, pls add this parameter: 'required_same_host' => true in return as subscribeAction in src/Blogger/BlogBundle/Controller/PageController.php

**Comment by Hoannv** [comment]
@jamiemax I done backend, you should manage frontend for now.

**Comment by jamiemax** [comment]
hi hoan, thanks for this, however we also need to restrict access to the payment pages, so "subscribe", "events" and "products". When a user visits these pages they should see a message prompting them to visit their home site INSTEAD of the page. They must NOT be allowed to purchase, subscribe or book events in another country

**Comment by Hoannv** [comment]
yes, you can view message when you view these pages if you are in different site. Pls pull the latest commit on branch MF35

**Comment by jamiemax** [comment]
ok cool, I can see that on the subscribe and products pages now. but we also need it on the events page

**Comment by Hoannv** [comment]
yes, when you view event detail page, you can also see message

**Comment by jamiemax** [comment]
ok cool. I understand now. thanks
