### ISSUE TITLE
emails are not sent to customers on subscr_failed

### ISSUE THREAD

**Issue by jamiemax** [gemstoneit/metafit2014#36]
it seems that automatic emails to customers are not being triggered when subscr_failed 

possibly the IPN is not being received?
possibly it is not being handled correctly?

could you look into it?

**Comment by Hoannv** [comment]
I'll re-check. Can you confirm you still get email of other events ?

**Comment by jamiemax** [comment]
it seems this is actually working, the problem is that some users are not associated with a paypal subscription. I'm going to close this for now
