### ISSUE TITLE
Add a new Subscription entity

### ISSUE THREAD

**Issue by jamiemax** [gemstoneit/metafit2014#37]
I've changed my mind about this. Could we have a new "Subscription" entity?

This should have the following fields:

subscription_id
subscription_type
subscription_status

the user table should have a foreign key field called 'user'

could you set this up?

**Comment by Hoannv** [comment]
I think we should add this field to user table. This task takes 1 hour

**Comment by jamiemax** [comment]
ok sure. can you go ahead with this please

**Comment by jamiemax** [comment]
actually can you hold off on this for a moment

**Comment by Hoannv** [comment]
Fortunately, I just read it :laughing:

**Comment by jamiemax** [comment]
ha cool

**Comment by jamiemax** [comment]
ok so instead of a paypal email attribute, can we have a subscr_id attribute?
