### ISSUE TITLE
Corporate user groups

### ISSUE THREAD

**Issue by jamiemax** [gemstoneit/metafit2014#38]
Some users subscribe to Metafit as part of a large group through their company. We want to be able to add corporate member groups which we can assign large numbers of users to, and give access privileges to these groups.

So for example we could have a group called "XYZ Gym Company", which we could assign 100 users to. We would grant "Coach" privileges to "XYZ Gym Company"  and all users within this group would automatically be able to access the pages that are restricted to the "coach" group.

Could you give me a quote for setting up this functionality?

**Comment by Hoannv** [comment]
Can you explain who add users to groups? If admin adds users to group, it takes less than 2 hour.

**Comment by jamiemax** [comment]
yes it would be the admins who add users to groups.

**Comment by jamiemax** [comment]
client has approved this, please go ahead

**Comment by Hoannv** [comment]
Admin can go admin dashboard and create new "group" entity now. Pls choose "external" category for company group. Internal category for metafit group.
