### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by jamiemax** [gemstoneit/metafit2014#39]
Hi Hoan, we want to be able to translate sections of the templates, based on Site ID. I was reading this article and it sounds like this could be the kind of thing we are looking for http://symfony.com/doc/current/book/translation.html

I can add all the translations in myself, but I would need you to set up the functionlity for me to add them.

Can you let me know what you think and how long it would take?

**Comment by Hoannv** [comment]
1 hour for setup translation

**Comment by jamiemax** [comment]
great, please go ahead

**Comment by Hoannv** [comment]
1 hour for setup translation, you must translate all content to different languages yourselves

**Comment by jamiemax** [comment]
that's fine - can you let me know where to put the translations?

**Comment by Hoannv** [comment]
ok, I will setup and show you where to put the translations.

**Comment by Hoannv** [comment]
I add language field in site entity. Admin can change language of each site in admin dashboard.

If you need translate any text, you should follow symfony translation syntax and add translation in src/Blogger/BlogBundle/Resources/translations/ for each language

**Comment by Hoannv** [comment]
You should remove cache: app/cache/dev if translation is not working.

**Comment by jamiemax** [comment]
that looks great, thanks very much. i'll close this now and i'll let you know if I have any issues
