### ISSUE TITLE
duplication of code in controllers

### ISSUE THREAD

**Issue by jamiemax** [gemstoneit/metafit2014#40]
We seem to have a lot of duplicated code in controllers, as there is a lot of data that we need to pass to all templates. for example we have the following code in almost every action method:

        // get the site
        $siteId = $this->get('site.get')->getSite($request->getHost(), $em);
        $site = $em->getRepository('BloggerBlogBundle:Site')->find($siteId);

        // get the menu for this site
        $menu = $this->get('menu.get')->getMenu($siteId);
        $footerMenu = $this->get('menu.get')->getMenu($siteId, 2);

I've just added the footerMenu variable and I had to go through every action and add it in manually

My question is: is there a way to get all of this data in a parent class and have all the other controllers inherit from it?

**Comment by Hoannv** [comment]
yes, you can create twig function for generating menu and footer menu.

**Comment by Hoannv** [comment]
Do you need help ?

**Comment by jamiemax** [comment]
no that's fine, i'll work on this
