### ISSUE TITLE
Remove COACH group and allow users access if they have an 'active' SUBSCRIPTION record

### ISSUE THREAD

**Issue by jamiemax** [gemstoneit/metafit2014#62]
Hi Hoan,

We want to make a big change to the way users are given access to materials on the Metafit site.

CURRENT SITUATION - we have the levels:

User
...can book courses
New coach
...can subscribe
Coach
...can view workouts/tracks/media files

OBJECTIVE:

We want to REMOVE the "coach" level and instead allow users access to the workouts/tracks/media files based on their SUBSCRIPTION record in the database.

The logic is as follows:

if USER has SUBSCRIPTION with status ACTIVE
...then allow them access to workouts/media pack/video library/etc

if USER has SUBSCRIPTION with status DISABLED
...then do NOT allow access to workouts/media pack/video library/etc
...show a message stating: "Your subscription has been deactivated, please resubscribe through the 'subscribe' page"

Will this be possible to achieve?

Thanks,
Jamie

**Comment by Hoannv** [comment]
why we need remove "COACH" role ?

For accessing workouts/tracks/media files, we only require user has active subscription. If use has active subscription, they can access these resources.

**Comment by jamiemax** [comment]
ok - what is the coach role used for then?

**Comment by Hoannv** [comment]
I saw coach role is in many places. If we remove it, we must spend much time to verify can check functions.

**Comment by jamiemax** [comment]
ok fine - i want the coach role to be redundant though, access should be dependent **only** on having an active subscription - is that ok?

**Comment by jamiemax** [comment]
how long would it take to do this?

**Comment by Hoannv** [comment]
it's take about 5-6 hours

**Comment by jamiemax** [comment]
ok please go ahead with this

**Comment by Hoannv** [comment]
I updated requirement for access pages base on subscription. But I have some questions before deploy it:

Users on corporate groups couldn't able to access workouts/tracks/media files because they don't have active subscription.

If we remove ROLE_COACH, it means we also remove coach group. We couldn't able to send email to this group.

**Comment by jamiemax** [comment]
Thanks for this, here are my thoughts:

*Users on corporate groups couldn't able to access workouts/tracks/media files because they don't have active subscription.*

Can we add another property to the subscription entity: "group" - this should be linked to the "group" entity. So SUBSCRIPTIONS can either be linked to GROUPS or USERS.

The logic should be as follows:

If USER has active SUBSCRIPTION, allow access
else if USER has GROUP with active SUBSCRIPTION, allow access
else deny access

*If we remove ROLE_COACH, it means we also remove coach group. We couldn't able to send email to this group.*

Can we add logic to look up users with active subscription, instead of users in coach group, then email to all users with active subscription?

**Comment by Hoannv** [comment]
We keep ROLE_COACH, so we can easily look up coach for sending email.

**Comment by Hoannv** [comment]
Pls recheck before deploy it.
