### ISSUE TITLE
Add WYSIWYG editor to email admin

### ISSUE THREAD

**Issue by jamiemax** [gemstoneit/metafit2014#64]

**Comment by jamiemax** [comment]
Hi Hoan,
In Sonata, we want to implement a WYSIWYG editor on the "text" property of the "Email" element for creating emails.
I was thinking TinyMCE might be a good way to go with this, as you can see on the link below there is a "legacyoutput" plugin which can be used for generating HTML for emails. Or if you know of another better way then let me know
If you can give me an estimate that would be great
http://www.tinymce.com/wiki.php/Plugin:legacyoutput

**Comment by Hoannv** [comment]
I think ckeditor is best choice.

Do we need upload image function on WYSIWYG editor ?

**Comment by Hoannv** [comment]
Do you have feedback for this issue ?

**Comment by jamiemax** [comment]
not yet - need to check with the client

**Comment by Hoannv** [comment]
agreed

**Comment by jamiemax** [comment]
is ckeditor suitable for HTML emails? If we had the image upload function then how much time would it take to implement?

**Comment by Hoannv** [comment]
I believe both tinymce and ckeditor are suitable for email builder.

**Comment by Hoannv** [comment]
Hi @jamiemax,

Can you confirm this task?
