### ISSUE TITLE
Add cookie notification

### ISSUE THREAD

**Issue by jamiemax** [gemstoneit/metafit2014#71]
Can we implement the notification described here? This is only necessary on the UK, France, Denmark and Slovakia sites.

http://cookiesdirective.com/

**Comment by Hoannv** [comment]
0.5 hours

**Comment by jamiemax** [comment]
please go ahead with this

**Comment by Hoannv** [comment]
@jamiemax I added script. You can add message and translate message for each site.

**Comment by jamiemax** [comment]
great
