### ISSUE TITLE
Expiry date for corporate groups

### ISSUE THREAD

**Issue by jamiemax** [gemstoneit/metafit2014#72]
Hi Hoan, we need to add an expiry date for corporate groups.

Requirements:

An extra datetime property in the group entity called "Expiry Date"
After that date, the users in that group will no longer have access to the site

**Comment by jamiemax** [comment]
could i have a quote for this?

**Comment by Hoannv** [comment]
It takes 1 hour

**Comment by jamiemax** [comment]
please go ahead with this

**Comment by Hoannv** [comment]
"After that date, the users in that group will no longer have access to the site"

**Comment by jamiemax** [comment]
no this is an additional condition. users groups must have an active subscription AND the current date must be less than the expiry date

**Comment by Hoannv** [comment]
the users in that group will no longer have access to the site. What do you mean ?

**Comment by jamiemax** [comment]
Actually, I've just had an idea.

Instead can we add an optional EXPIRY DATE field to the SUBSCRIPTION entity.

The condition should be:

IF subscription.status = ACTIVE
AND subscription.expiry_date > (current date)
THEN allow access

ELSE Deny access.

**Comment by jamiemax** [comment]
if the expiry date field is NULL then it should be ignored

**Comment by Hoannv** [comment]
agreed with you

**Comment by jamiemax** [comment]
ok great

**Comment by Hoannv** [comment]
@jamiemax you can check this function now.

**Comment by jamiemax** [comment]
looks good, thanks
