### ISSUE TITLE
In admin, only show specific records, depending on who is logged in

### ISSUE THREAD

**Issue by jamiemax** [gemstoneit/metafit2014#8]
The Blog and Event entities both have a property called Site, which refers to the Site entity

Currently we have a master admin user in the UK, and another admin user in Australia

Objective: When the Australian admin user logs into the Sonata admin CRUD, I want him to ONLY be able to see (and edit) the Blogs and Events which are linked to the Australian site (ID 2)

**Comment by Hoannv** [comment]
@jamiemax you can promote an user becomes a site manager by adding "site manager" for him/her.

The go to sites, add site managers for these sites. These managers will be able view/edit page, price, event, booking of these sites.
