### ISSUE TITLE
Add subscription details to frontend account manager

### ISSUE THREAD

**Issue by jamiemax** [gemstoneit/metafit2014#80]

**Comment by jamiemax** [comment]
@dantulloch Hi Dan -  i've added a table of user subscriptions to the My Metafit/Manage my account page. If you could style it up that would be brill.

**Comment by jamiemax** [comment]
it's on branch MF80 so probably best if you edit that one

**Comment by dantulloch** [comment]
![screen shot 2015-07-17 at 22 48 25](https://cloud.githubusercontent.com/assets/1451551/8757913/4d761fce-2cd6-11e5-853a-c926aa806c43.png)
![screen shot 2015-07-17 at 22 48 25](https://cloud.githubusercontent.com/assets/1451551/8757914/4f8c11c4-2cd6-11e5-8cb9-d05e657528fd.png)

**Comment by dantulloch** [comment]
Mobile View 
![screen shot 2015-07-17 at 22 48 15](https://cloud.githubusercontent.com/assets/1451551/8757929/637a3b0c-2cd6-11e5-9b4b-6286ff3b3478.png)

**Comment by dantulloch** [comment]
Simplified for mobile and fully tested. Is in MET-3. Can't access JIRA so couldn't update on there
